### ISSUE TITLE
R3det is not in the detector registry

### ISSUE THREAD

**Issue by TeleeMa** [SJTU-Thinklab-Det/r3det-on-mmdetection#3]
Failed to train on R3Det* mmdetection version based on PyTorch. I got an import error when running sh rtools/train.sh

Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 134, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/xs/mtl/r3det-on-mmdetection-master/mmdetection-2.2.1/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/xs/mtl/r3det-on-mmdetection-master/mmdetection-2.2.1/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/xs/.conda/envs/torch140/lib/python3.6/site-packages/mmcv/utils/registry.py", line 157, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'R3Det is not in the detector registry'

Besides, I install mmdetection from [https://github.com/open-mmlab/mmdetection](url), because your setup.py installation failed in my device and I found the reason that mmdetection 2.2.1 is needed. So I guess my problem may caused by not using your setup.py?

My environment is :
Pytorch: 1.4.0
Python: 3.6.10
CUDA: 10.0
GCC: 7.3.0

**Comment by TeleeMa** [comment]
And if I use your setup.py, it shows as : 
gcc: error: mmdet/ops/nms/src/rnms_ext.cpp: No such file or directory

**Comment by tianbinli** [comment]
you can try to solve this by installing  mmcv0.5.9

**Comment by Theodoric008** [comment]
u should run setup.py, not just mmdet

**Comment by colorfully-ybf** [comment]
您好 我也是这个问题 但是我是run的setup.py 也没有报错 我猜测会不会是显卡的问题？作者使用的是20系显卡和10的cuda 我的环境是30系显卡和11的cuda。那应该怎么解决？
