### ISSUE TITLE
Got this error when run the command "python setup.py install"

### ISSUE THREAD

**Issue by hopesala** [SJTU-Thinklab-Det/r3det-on-mmdetection#6]
File "/home/cao/anaconda3/envs/open-mmlab/lib/python3.7/distutils/command/build_ext.py", line 363, in check_extensions_list
    "each element of 'ext_modules' option must be an "
distutils.errors.DistutilsSetupError: each element of 'ext_modules' option must be an Extension instance or 2-tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 329, in <module>
    zip_safe=False)
  File "/home/cao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup

**Comment by YangHai-1218** [comment]
I also got this error, have you fixed it?

**Comment by CathyShang** [comment]
I got this error, too. Have you solve it?
